# References: https://www.cloudways.com/blog/php-continuous-integration-travis-ci/
# References: https://docs.travis-ci.com/user/notifications/
# References: https://gist.github.com/gilbitron/5cac0ac5fa07e9b354ac
# References: https://docs.travis-ci.com/user/sonarcloud/
# References: https://medium.com/@felipeluizsoares/automatically-deploy-with-travis-ci-and-heroku-ddba1361647f
# References: https://mattstauffer.com/blog/laravel-on-heroku-using-a-postgresql-database/

dist: trusty

language: php

php:
  - 7.2.10

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - npm install
  - php artisan key:generate
  - php artisan migrate --force
  - composer dump-autoload
  - php artisan db:seed --force
  - php artisan passport:install

script:
  - vendor/bin/phpunit

matrix:
  fast_finish: true