dist: trusty
language: php
php:
- 7.2.10
before_script:
- cp .env.travis .env
- composer self-update
- composer install --no-interaction
- npm install
- php artisan key:generate
- php artisan passport:install
- php artisan migrate
script:
- vendor/bin/phpunit
cache:
  directories:
  - "$HOME/.composer/cache/files"
matrix:
  fast_finish: true
notifications:
  slack:
    rooms:
      secure: HD37dndzhf9YqECoDvQNB+Pgn2UVFerGFW79dEu7CEPGYBCJOqBn9AkLBMa575/rgdHgtXPmebPIJzz0DCSdm3KHRWj9XyRVYYG0u4VsF9ammrv0AwOwJRLPoEdS4ozUrVGXR3acnqCkIDCNXoOVXOqEye6LEduoYAlrYTKWPYWtVhjbNGSmFeOe4dneqO/1Fq+12LsRqmTaRi1tmw1xq5kaKYMC63ZewW655DsXC1ybdTTXL7gMImLLiOYwFYp5+/QK31HdChBV1bpm7SLCMqSVGjKYNINEYxtfWkZ9Rr+651dZ9km2XAzgXt4HDaNi2OoNu+j/UoZKr+IC6ycSLGIhGkfegjGKu6C5NYBYF26Pv3wryGzRc7Rmx5wBAqL1xYygUnYQDYx0zsBYLwkp2CSa2qThCMzDoeRDLc5zSjUiLfWVIszsCMkY8YLN4WUS+dC81k4yMHCjBOyfx8Qs+ohGTeJX2bYcrGnobuPuGpRr2rzlt19QunY2Zpx6U/lS6xoolDlHCTWKaAw4NBDlc1E+OEteCYlOrTqaQyoNV9bsv5xWEJFy62w8afWW9BCbykv2ukQRUAJLuC2eFEzwbLYVCCuTSrxMdDI9P1sXF6KvuQ4ayENkppUTJY5+zRaPowSAXVVElJN0Y3Ur95tjGkyVIXP/7QW/HRrQdPSRQ7c=
    on_failure: always
    on_success: change
addons:
  sonarcloud:
    organization: "dejongyeong-github"
    token:
      secure: ZiGJKQZArYkE/J2QyNg3wB8M3woPg+VplE348Z2RAMHcCh0DtM7KBjoiN92Ne1M5k4Yycz92wjbJaNFLMeJGYgDsT26suC1pEco7FRqZfJXAczeCXzGTt7ejBSfjW3+hGUo5XUFDpSpKhyS3CMRf0AVNXNCtm7wzwSUBByEwFhohTJCkWjvJh+Id92P1lzvC3LxMtbAidS4lrAF9r9KwoqLiPHDr4mnztjdjpmL0echSjYk5fCzrcyngWbxo7zEHTzAepzPyTTzPHLVwK84yXVGWm9eMCeSboa5iZyq3BO15rJbT/1KPuQ9c/PHGSPsPjDJVkCm098vQVQpb75fKRB1rvgGugeRVaNx5XR6QTDZmc2fSstaH/kWAQL6NxEw0kfgM76u8OpyRE66QYY83oUk4a4j9keQEzUXrBNAeC06Fjlt84OONAZ/POAHNJTVffbhdz3b5nQFreo4GD3bk0XKTyB4Rp8+9ULU/w1J1rhPuKWOp8gSOsZXHN2nhduExLCcOwXT8KdS5BQOh5OFaiGmoSMsap/h1J1u6BqvWnITUIjjeTE9e3QVrnIPByI9ucCU7pUBcxAmcG1VL355AHZn1XK/hkkkGhOPVmORaIGT86idJw/WF+7Hnsq2AJhv8cQkqrg47HKV9GFRmj3XwarEHwLTNwtl1EMkLA+RRJu0=