version: 2

jobs:
  deploy-job:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "65:91:af:42:b1:06:61:7b:66:76:d5:c8:1f:3f:52:6d"
  build:
    docker:
      - image: library/php:7.2-rc
      - image: postgres:11
        environment:
          - POSTGRES_USER=postgres
    working_directory: ~/repo
    steps: 
      - checkout
      - run:
        name: Install PostgreSQL client tools
        command: |
          sudo apt-get update && sudo apt-get install postgresql-client
      - run:
        name: Install and Enable pdo_pgsql php extension
        command: |
          sudo apt-get update && sudo apt-get install libpq-dev
          sudo docker-php-ext-install pdo_pgsql && sudo docker-php-ext-enable pdo_pgsql
      - run:
        name: Update composer
        command: sudo composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-
      - run:
          name: Install php dependencies
          command: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run:
          name: Prep the database and user, install extensions etc.
          command: |
            sudo -u root psql -h 127.0.0.1 -U postgres -c "create database homestead"
            sudo -u root psql -h 127.0.0.1 -U postgres -c "create user homestead password 'secret'"
            sudo -u root psql -h 127.0.0.1 -U postgres -c "grant all on database homestead to homestead"
            sudo -u root psql -h 127.0.0.1 -U postgres homestead -c "create extension citext"
      - run:
          name: Populate .env
          command: cp .env.example .env && php artisan key:generate
      - run:
          name: Run database migrations
          command: php artisan migrate --seed --force
      - run:
          name: Run tests
          command: ./vendor/bin/phpunit

      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples   